# Matrixrechnung

## Generelles:
Importieren Sie zunächst die mathematischen Pakete. Denken Sie daran, diese Imports jedes mal als erstes auszuführen!

In [21]:
from scipy import *
from pylab import *
from numpy import *

## Matrizen in Python: Grundlegende Operationen
Matrizen werden in Python als 2D-arrays dargestellt. Sie können beispielsweise direkt zwei 2x2 Matrizen erstellen.

In [22]:
A = array([[1, 2], [3, 4]])
B = array([[5, 6], [7, 8]])

print(A)
print(B)

# Element Zugriff
a = A[0, 0] # 1
b = A[0, 1] # 2
c = A[1, 0] # 3
d = A[1, 1] # 4

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


Die üblichen Operationen sind von numpy schon definiert: Addition, Subtraktion, Multiplikation, Transponieren

In [23]:
# Matrix addition
C = A + B
print("A + B =\n", C)

# Matrix subtraction
D = A - B
print("A - B =\n", D)

# Matrix multiplication
E = A @ B
print("A @ B =\n", E)
# or
F = dot(A, B)
print("dot(A, B) =\n", F)

# Transponierte Matrix
G = A.T
print("A.T =\n", G)

A + B =
 [[ 6  8]
 [10 12]]
A - B =
 [[-4 -4]
 [-4 -4]]
A @ B =
 [[19 22]
 [43 50]]
dot(A, B) =
 [[19 22]
 [43 50]]
A.T =
 [[1 3]
 [2 4]]


Sie können auch direkt Matrizen einer bestimmten Größe mit festgelegten Einträgen erzeugen lassen:

In [24]:
# Nullmatrix der Größe 4x5
G = zeros((4, 5))
print("zeros((4, 5)) =\n", G)

# Einheitsmatrix der Größe 3x3
H = eye(3)
print("eye(3) =\n", H)

# Diagonalmatrix
I = diag([1, 2, 3])
print("diag([1, 2, 3]) =\n", I)

# Matrix mit einsen
J = ones((2, 3))
print("ones((2, 3)) =\n", J)

zeros((4, 5)) =
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
eye(3) =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
diag([1, 2, 3]) =
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
ones((2, 3)) =
 [[1. 1. 1.]
 [1. 1. 1.]]


### Aufgabe:
Führen Sie die folgenden Matrix-Multiplikationen aus. Vergleiche  Sie die Ergebnisse Stichprobenartig mit handschriftlichen Lösungen:

$$
\begin{array}{cc}
\text{a)} \begin{pmatrix}
-2 & 3 & 1 \\
6 & -9 & -3 \\
4 & -6 & -2
\end{pmatrix}
\begin{pmatrix}
3 & 1 & 1 \\
2 & 0 & 1 \\
0 & 2 & -1
\end{pmatrix} &
\text{b)} \begin{pmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
4 & 0 & 0
\end{pmatrix}
\begin{pmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
4 & 0 & 0
\end{pmatrix} \\
\\
\text{c)} \begin{pmatrix}
1 & 1 \\
1 & 1
\end{pmatrix}
\begin{pmatrix}
1 & 1 \\
2 & 4
\end{pmatrix} &
\text{d)} \begin{pmatrix}
1 & 1 \\
1 & 1
\end{pmatrix}
\begin{pmatrix}
0 & 1 \\
3 & 3
\end{pmatrix}
\end{array}
$$

In [26]:
# TODO
A1 = array([[-2, 3, 1], [6, -9, -3], [4, -6, -2]])
A2 = array([[3, 1, 1], [2, 0, -1], [0, 2, -1]])


print(A1)
print(A2)
print(A1 @ A2)

[[-2  3  1]
 [ 6 -9 -3]
 [ 4 -6 -2]]
[[ 3  1  1]
 [ 2  0 -1]
 [ 0  2 -1]]
[[ 0  0 -6]
 [ 0  0 18]
 [ 0  0 12]]


### Zugriff auf Zeilen oder Spalten einer Matrix
Numpy Arrays unterstützten das sogenannte array-slicing. Damit können Sie sehr komfortabel auf Zeilen oder Spalten von Matrizen zugreifen. Dafür geben Sie als zweiten Index einfach einen Doppelpunkt an:

In [30]:
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9],[7, 8, 9]])
print("A =\n", A)

# Zeilen und Spalten
print("A[0, :] =", A[0, :])
print("A[:, 0] =", A[:, 0])

# Sie koennen auch die Zeilen und Spalten von Matrizen aendern
A[0, :] = [10, 11, 12] # Erste Zeile
A[1, :] = 2 * A[0, :] # Zweite Zeile ist das Doppelte der ersten Zeile
print("A =\n", A)

# Falls noetig koennen Sie auch die Dimensionen einer Matrix auslesen
numRows = A.shape[0]
numCols = A.shape[1]
print(numRows)
print(numCols)

A =
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [7 8 9]]
A[0, :] = [1 2 3]
A[:, 0] = [1 4 7 7]
A =
 [[10 11 12]
 [20 22 24]
 [ 7  8  9]
 [ 7  8  9]]
4
3


## Lösung von linearen Gleichungssystemen

### Gauß-Jordan-Algorithmus
Nutzen Sie jetzt das bislang gelernte, um den in der Vorlesung besprochenen Gauß-Jordan-Algorithmus zur Lösung von linearen Gleichungssystemen zu implementieren. Eingabewerte sind dabei eine Matrix $A$ und eine rechte Seite $\vec b$, Rückgabewert ist der Vektor $\vec x$, so dass $A\cdot \vec x=\vec b$.

Sie brauchen nur den Fall berücksichtigen, dass die Lösung des LGS eindeutig möglich ist.

In [ ]:
def gauss(A, b):
  # TODO: Implementieren Sie den Gauß-Algorithmus
  return x

Lösen Sie jetzt mit Ihrem Gauß-Algorithmus das LGS $$\begin{pmatrix}
1 & 1 & 1 \\
2 & 4 & 3 \\
3 & -1 & 4
\end{pmatrix}\cdot\begin{pmatrix}
x_1 \\ x_2 \\ x_3
\end{pmatrix} = \begin{pmatrix}
2 \\ -1 \\ 7
\end{pmatrix}$$

In [ ]:
# TODO: Testen Sie Ihre Implementierung

Hinweis: die richtige Lösung ist $\begin{pmatrix}
6 \\
-1 \\
3
\end{pmatrix}$

### Lösen von LGS mit numpy
Helps.In numpy gibt es natürlich schon vorgefertige Algorithmen, die Ihnen das lösen von LGS erlauben. Wenn Sie keine besonderen Anforderungen haben, können Sie in der Regel numpy.linalg.solve dafür verwenden.

In [ ]:
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = array([1, 2, 3])

# Loesen des Gleichungssystem Ax = b
x = linalg.solve(A, b)
print("x =\n", x)

# Probe
b2 = A @ x
print("b2 =\n", b2)

## Berechnung von Determinanten
Auch die Berechnung von Determinanten ist natürlich in numpy bereits vorhanden.
Beachten Sie dass aufgrund von Rundungsfehlern die Determinante einer nicht-invertierbaren Matrix häufig nicht exakt 0 ist, sondern nur 0 im Rahmen der numerischen Genauigkeit.

In [ ]:
# Determinante einer invertierbaren Matrix
A = array([[1, 2, 4], [2, 1, 3], [5, 6, 8]])
detA = linalg.det(A)
print("det(A) =", detA)

# Determinante einer nicht invertierbaren Matrix
B = array(([1,2,3], [4,5,6], [7,8,9]))
detB = linalg.det(B)
print("det(B) =", detB)

## Inverse Matrix
Das Invertieren von Matrizen ist grundsätzlich möglich, aber numerisch instabil und wird daher in der Regel nicht gemacht.

In [ ]:
A = array([[1, 2], [3, 4]])

A_inv = linalg.inv(A)
print("A_inv =\n", A_inv)

# Probe
I = A @ A_inv
print("I =\n", I)

# Lösen von linearen Gleichungssystemen
b = array([1, 2])
x = A_inv @ b
print("x =\n", x)

### Numerische Stabilität
Hier sehen Sie ein Beispiel, für das das numerische Invertieren nicht zum richtigen Ergebnis führt. Sie können sehen, dass die Probe nichts mehr mit der ursprünglichen rechten Seite zu tun  hat.

In [ ]:
# Erstellt eine Hilbert-Matrix – bekannt für schlechte Konditionierung
n = 100
hilbert_matrix = array([[1 / (i + j + 1) for j in range(n)] for i in range(n)])

# Berechne die Inverse mit numpy.linalg.inv
inverse_matrix = linalg.inv(hilbert_matrix)

# Probe
I = hilbert_matrix @ inverse_matrix
print("Erste Zeile von I sollte (1, 0, 0, 0, ...) sein, ist aber \n", I[0, :10])

# Loesung eines LGS mit der Inversen
b = arange(1, n + 1)
x = inverse_matrix @ b

# Probe
b2 = hilbert_matrix @ x
print("b2 ist vollkommen unbrauchbar, sollte (1,2,3,...) sein, ist aber =\n", b2[:10])

Das Lösen des LGS ist aber natürlich auf für diese schlecht konditionierte Matrix möglich und führt zum korrekten Ergebnis:

In [ ]:
x = linalg.solve(hilbert_matrix, b)
b2 = hilbert_matrix @ x
print("b2 ist nun im wesentlichen korrekt =\n", b2[:10])

Probieren Sie doch einmal Ihren eigenen Gauß-Algorithmus für dieses LGS aus. Funktioniert er?

In [ ]:
# TODO